spring:
  datasource:
    username: abra
    password: abra
    url: jdbc:mysql://localhost:3306/abra
    
  jpa:
    hiberante:
      ddl-auto: none
    show-sql: true
  
  sql:
    init:
      mode: never